### ISSUE TITLE
what is fusion_report sync?

### ISSUE THREAD

**Issue by anoronh4** [Clinical-Genomics/fusion-report#57]
I found the fusion_report sync function but there isn't a clear explanation for what it does, and it doesn't seem to work or change any files in the database path. i'm wondering if this function is deprecated or if there's an explanation somewhere for it.

**Comment by matq007** [comment]
Hi, the `sync` was previously used to redownload all the databases and compress them into one zip file which I would normally upload on sourceforce. As you can see I haven't really been active with the development, there have been some forks here and there. I started last year with complete re-design, but haven't finished yet.

**Comment by rannick** [comment]
Outdated, closing, feel free to reopen if necessary
