### ISSUE TITLE
Fusion_report download issue

### ISSUE THREAD

**Issue by APL-MolecularPathology** [Clinical-Genomics/fusion-report#72]
I used the following command to download the dbs for fusion_report:

fusion_report download --cosmic_usr *** --cosmic_passwd **** output /data/rnafusion_ref

the folder rnafusion_ref contained all the custom references I have spent the last 3 weeks building to run with the nf-core/rnafusion pipeline. 

It was mentioned in nf-core/rnafusion issues that the .db files needed to be found in the -genome_base designated folder which is why I designated the download output location as /data/rnafusion_ref. 

While I was able to download the dbs, this command erased all the files and folders in my reference location. So back to square 1...

**Comment by apeltzer** [comment]
Also not working with the commercial option unfortunately.

**Comment by rannick** [comment]
Sorry to hear this. There is indeed a clean all files but the databases in the output directory provided. There is a reason it was implemented (presence of hidden MACOS_DIR on mac for example), but it can be done better to avoid this to ever happen
