### ISSUE TITLE
Fusion report fusiongdb.db missing

### ISSUE THREAD

**Issue by lieselfitz** [Clinical-Genomics/fusion-report#75]
Hi, 
Apologies in advance but I am not a bioinformatician, so this question may be very naive!  Although, I have consulted with our group's bioinformatician and he also has the same issue.

When we try to build the references, we are only getting three of the four fusion report files (cosmic.db, mitelman.db and fusiongdb2.db.  The fourth file, fusiongdb.db isn't being built.  This is the code we are using:

#!/usr/bin/bash -l
#PBS -N USER
#PBS -M email@address
#PBS -m abe
#PBS -l select=1:ncpus=50:mem=300gb
#PBS -l walltime=80:00:00

### Initialisation

date

module load rosalind gcc-env nextflow/23.10.1 java/jdk-18.0.2 singularity

cd /u/folder/RNA_fusion

nextflow run nf-core/rnafusion \
-profile singularity \
-r 3.0.2 \
--build_references --all \
--cosmic_username email@address --cosmic_passwd ****** \
--genomes_base /u/folder/RNA_fusion \
--outdir /u/folder/RNA_fusion \

date

In the nextflow log, there seems to be errors fairly early on.  I'm not sure how much detail you need (the whole file?) but below is an extract of output where the first errors occur:

May-31 09:27:45.244 [Task submitter] INFO  nextflow.Session - [02/cdbe39] Submitted process > NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONCATCHER_DOWNLOAD (fusioncatcher_download)
May-31 09:28:55.339 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONREPORT_DOWNLOAD (fusionreport); status: COMPLETED; exit: 0; error: -; workDir: /u/lieself/RNA_fusion/work/26/886fe3ba4b0894e62ef7aca6a89bc5]
May-31 09:28:55.368 [Task monitor] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'PublishDir' minSize=10; maxSize=384; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
May-31 09:30:02.876 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 3; name: NFCORE_RNAFUSION:BUILD_REFERENCES:HGNC_DOWNLOAD (hgnc); status: COMPLETED; exit: 0; error: -; workDir: /u/lieself/RNA_fusion/work/68/36fe7a32c1709e1b063df491734877]
May-31 09:32:31.413 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 3 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: NFCORE_RNAFUSION:BUILD_REFERENCES:ARRIBA_DOWNLOAD (arriba); status: RUNNING; exit: -; error: -; workDir: /u/lieself/RNA_fusion/work/8f/00d2e7de186488a100ec273b6909ac]
~> TaskHandler[id: 5; name: NFCORE_RNAFUSION:BUILD_REFERENCES:ENSEMBL_DOWNLOAD (ensembl); status: RUNNING; exit: -; error: -; workDir: /u/lieself/RNA_fusion/work/54/fb3df1ccb2ad49176b2c3dca934fed]
~> TaskHandler[id: 4; name: NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONCATCHER_DOWNLOAD (fusioncatcher_download); status: RUNNING; exit: -; error: -; workDir: /u/lieself/RNA_fusion/work/02/cdbe39750a43c4f90002b82d48a690]
May-31 09:34:24.426 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: NFCORE_RNAFUSION:BUILD_REFERENCES:ARRIBA_DOWNLOAD (arriba); status: COMPLETED; exit: 0; error: -; workDir: /u/lieself/RNA_fusion/work/8f/00d2e7de186488a100ec273b6909ac]
May-31 09:37:05.153 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 5; name: NFCORE_RNAFUSION:BUILD_REFERENCES:ENSEMBL_DOWNLOAD (ensembl); status: COMPLETED; exit: 0; error: -; workDir: /u/lieself/RNA_fusion/work/54/fb3df1ccb2ad49176b2c3dca934fed]

I have still tried running the fusion pipeline with the three .db files, and some fusion output is provided.  I'm just a little dubious of the results as a very common fusion gene is not present in any of the transcriptomes I've analysed to date.

Again, apologies if I've provided too little or too much information.  I'm sure I'm doing something very obviously wrong, I just can't work it out!
thank you, Liesel

**Comment by rannick** [comment]
Hi! 
I will have a look into fusiongdb.db, sometimes the paths are updated and fusion-report is not able to fetch them any more.
 
However, you should be able to see the fusions even without fusiongdb.db present, so I am wondering if there is another underlying issue (to open in https://github.com/nf-core/rnafusion/issues)

**Comment by rannick** [comment]
Ok that is an easy one, the latest update of fusion-report dropped fusiongdb.db as it did not bring more than fusiongdb2.db. In the log file excerpt you provided, I also see no errors. Simply, the documentation of rnafusion needs to be updated to remove references to fusiongdb.db. I am closing this here. If you encounter further error with the rnafusion pipeline, please open an issue in https://github.com/nf-core/rnafusion/issues.

**Comment by lieselfitz** [comment]
Fabulous, thank you so much Annick!  That is good to hear and I will look into the fusion output data we’re getting to see about the “missing” fusions.

Take care,
Liesel
